-- Auto-generated by update.lua
charpatternstart_address = 0x5D629D;
macropatternstart_address = 0x7047BF;

staticcharbase_address = 0x8F2B70;
staticmacrobase_address = 0x940E68;

charPtr_offset = 0x588;
camPtr_offset = 0x460;
mousePtr_offset = 0x6E4;
pawnId_offset = 0x18;
pawnType_offset = 0x1C;
charX_offset = 0x2C;
charY_offset = 0x30;
charZ_offset = 0x34;
chardirXUVec_offset = 0x38;
chardirYUVec_offset = 0x40;
charAlive_offset = 0x228;
castbar_offset = 0x25C;
charTargetPtr_offset = 0x278;
charPetPtr_offset = 0x284;
charName_offset = 0x294;
charHP_offset = 0x2CC;
charMaxHP_offset = 0x2D4;
charMP_offset = 0x2D8;
charMaxMP_offset = 0x2DC;
charMP2_offset = 0x2E0;
charMaxMP2_offset = 0x2E4;
charClass1_offset = 0x300;
charLevel_offset = 0x304;
charClass2_offset = 0x308;
charLevel2_offset = 0xE0C;
pawnAttackable_offset = 0x388;
inBattle_offset = 0x6D2;

camX_offset = 0x104;
camY_offset = 0x108;
camZ_offset = 0x10C;
camXUVec_offset = 0x128;
camYUVec_offset = 0x12C;
camZUVec_offset = 0x130;

macro1_offset = 0x110;
macro2_offset = 0x618;
