-- Auto-generated by update.lua
patternstart_address = 0x58BDB4;

staticcharbase_address = 0x88FF40;
charPtr_offset = 0x680; --OK
mousePtr_offset = 0x684; --OK
pawnId_offset = 0x18; -- OK
pawnType_offset = 0x1C; -- OK
charX_offset = 0x2C; -- OK
charY_offset = 0x30; -- OK
charZ_offset = 0x34; -- OK
camUVec1_offset = 0x38;
camUVec2_offset = 0x40;
charAlive_offset = 0x210; -- OK
castbar_offset = 0x244; -- OK
charTargetPtr_offset = 0x260; -- OK
charName_offset = 0x278; -- OK
charHP_offset = 0x290; --OK
charMaxHP_offset = 0x298; --OK
charMP_offset = 0x29C; -- OK
charMaxMP_offset = 0x2A0; -- OK
charMP2_offset = 0x2A4; -- OK
charMaxMP2_offset = 0x2A8; -- OK
charClass1_offset = 0x2C4; -- OK
charLevel_offset = 0x2C8; -- OK
charClass2_offset = 0x2D0; -- OK
charLevel2_offset = 0x2D0; -- OK
pawnAttackable_offset = 0x28E; --255 or 237 ==
inBattle_offset = 0x672; -- OK
