-- Auto-generated by update.lua
charpatternstart_address = 0x5D132D;
campatternstart_address = 0x58D930;

staticcharbase_address = 0x8D85E0;
staticcambase_address = 0x943610;

charPtr_offset = 0x588;
camPtr_offset = 0x460;
mousePtr_offset = 0x6B8;
pawnId_offset = 0x18;
pawnType_offset = 0x1C;
charX_offset = 0x2C;
charY_offset = 0x30;
charZ_offset = 0x34;
chardirXUVec_offset = 0x38;
chardirYUVec_offset = 0x40;
charAlive_offset = 0x224;
castbar_offset = 0x25C;
charTargetPtr_offset = 0x274;
charName_offset = 0x290;
charHP_offset = 0x2AC;
charMaxHP_offset = 0x2B4;
charMP_offset = 0x2B8;
charMaxMP_offset = 0x2BC;
charMP2_offset = 0x2C0;
charMaxMP2_offset = 0x2C4;
charClass1_offset = 0x2E0;
charLevel_offset = 0x2E4;
charClass2_offset = 0x2E8;
charLevel2_offset = 0x2EC;
pawnAttackable_offset = 0x2A8;
inBattle_offset = 0x6AA;

camX_offset = 0x100;
camY_offset = 0x104;
camZ_offset = 0x108;
camXUVec_offset = 0x124;
camYUVec_offset = 0x128;
camZUVec_offset = 0x12C;
